### ISSUE TITLE
Some question about functionality..

### ISSUE THREAD

**Issue by itProfi** [sticilface/ESP8266-wifi#10]
Cool project! But i have some question:
1. What's about this code:
""Fade", 
"Looparound", 
"Pick-Random", 
"Fadein-FadeOut", 
"Cool-Blobs", 
"Spiral",
"Test4",
"Squares",
"EQ1",
"Random-Function", 
"Art-Net", 
"Single-Colour-Fade", 
"Random-Colour-Fade", 
"HSIcycle", 
"New-Animations", 
};
const uint8_t numberofmodes(15); /////// DONT FORGET THIS....
"
when it's work? ))
2. In mode "Random-Colour" not work PWM (not adjustable brightness) - it's bug or no?
3. Waht's about page Test in webserver?
Thank you for you work!

**Comment by sticilface** [comment]
These are effects that I had and took out as they are just tests of functionality or didn't work, or planned but couldn't yet do, like eq.    There will be a lot of bugs as this one of my first sketches and it has just grown in size and complexity that i didn't initially plan for.  I've not started work on this project yet, but i've made a lib that can manage the wifi and will integrate it.  it uses ajax, and jquerymobile, which makes it very slick for controlling from mobile devices.  a lot better than what is here currently... so watch this space. 

I will take a look at the random colour option... might have to change how that works as it was a bit complicated... 

thanks for trying it out, let me know if u find any other issues.

**Comment by itProfi** [comment]
Ok, thank you for support and answer! And when can see you library ajax, and jquerymobile? Or it's only planned?

**Comment by sticilface** [comment]
it is only planned at the moment... but... all the backend is done..  it will basically be a total rebuild, and I understand C a little more now so hopefully it will be less buggy!!!

**Comment by sticilface** [comment]
I've started working on a total rewrite that should make understanding what is going on a LOT easier, and  reduce it to a few files.  Hopefully be a lot less buggy... I'm trying to work out how to manage effects that require different "rates" as some are limited by time delay through the loop and others are by animation speed in the neopixelbus..  getting there though
