### ISSUE TITLE
Feature request - audio spectrum analyzer :)

### ISSUE THREAD

**Issue by marksev1** [sticilface/ESP8266-wifi#2]
Great project you have here, when I saw all those cool effects that you have in your code I got and idea. What about if you would connect a microphone to the esp8266 which would then listen to beats and the leds on the ws2812 would pulsate with the sound. Maybe like this https://www.youtube.com/watch?v=8Urj9ugsV58 (but this one is a bit too fast flashing for my taste :) )
That would be really cool.

Otherwise good job. So via the MQTT it is probably possible to tie into Openhab for example and tie specific colours to specific actions?

**Comment by sticilface** [comment]
Cheers

This idea is in the works.  Not implemented yet, u may have seen the eq function.....

What was stopping me is that I need the analogue in to work so I can use the msgeq7. I have this chip working on an arduino (which I could attach to a digital in) but my plan was to have it  go via the adc. This is a bit unstable at the moment.  Or has been! 

You can have audio effects go via udp using pixel controller, or via dmx. So using a computer to output the sound. This is actually more desirable as U can control loads of them! Not just one! And it does work. This is another reason why I stopped developing a hardware solution.

**Comment by sticilface** [comment]
And yes, if openhab allows u to send ur own mqtt messages. I control 3 of them in my house using fhem.

**Comment by marksev1** [comment]
Nice, so there still is some hope for this to be implemented in the future? 

Are you controlling the leds through your browser via your phone, or do you have a special app?
